name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8 black

      - name: Run black (format and fix)
        run: black .

      - name: Run flake8 (check)
        run: flake8 .

      - name: Check for file changes
        id: git-check
        working-directory: .
        run: |
          if git diff --exit-code; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request with style fixes
        if: steps.git-check.outputs.changed == 'true' && github.ref == 'refs/heads/main'
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "style(black): format"
          title: "style(black): format"
          body: "The `black` action wants to apply these style."
          branch: "style/black"
          base: main
          signoff: true
          sign-commits: true
